# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AdidasCodingChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AdidasCodingChallenge

  pod 'Kingfisher'
  pod 'Cosmos'

  target 'AdidasCodingChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AdidasCodingChallengeUITests' do
    # Pods for testing
  end

end
